# Analysis Configuration - Eliminates Cross-Module Magic Values
# Centralizes all analysis parameters, thresholds, and behavioral settings

# Global Analysis Settings
analysis:
  default_policy: "standard"
  max_file_size_mb: 10
  max_analysis_time_seconds: 300
  parallel_workers: 4
  cache_enabled: true
  
# Quality Thresholds
quality_gates:
  overall_quality_threshold: 0.75
  critical_violation_limit: 0
  high_violation_limit: 5
  
  # Policy-specific thresholds
  policies:
    nasa-compliance:
      quality_threshold: 0.95
      violation_limits:
        critical: 0
        high: 0
        medium: 2
        low: 5
    strict:
      quality_threshold: 0.85
      violation_limits:
        critical: 0
        high: 2
        medium: 10
        low: 20
    standard:
      quality_threshold: 0.75
      violation_limits:
        critical: 0
        high: 5
        medium: 20
        low: 50
    lenient:
      quality_threshold: 0.60
      violation_limits:
        critical: 2
        high: 10
        medium: 50
        low: 100

# Connascence Weights and Scoring
connascence:
  type_weights:
    connascence_of_name: 1.0
    connascence_of_type: 1.5
    connascence_of_meaning: 2.0
    connascence_of_position: 2.5
    connascence_of_algorithm: 3.0
    connascence_of_execution: 4.0
    connascence_of_timing: 5.0
    connascence_of_values: 2.0
    connascence_of_identity: 3.5
  
  severity_multipliers:
    critical: 10.0
    high: 5.0
    medium: 2.0
    low: 1.0

# File Processing Configuration
file_processing:
  supported_extensions:
    - ".py"
    - ".pyx" 
    - ".pyi"
  
  exclusion_patterns:
    - "__pycache__"
    - ".git"
    - ".pytest_cache"
    - "node_modules"
    - ".venv"
    - "venv"
    - "build"
    - "dist"
    - ".tox"
    - "coverage"
  
  max_recursion_depth: 10
  follow_symlinks: false

# Error Handling Configuration
error_handling:
  continue_on_syntax_error: true
  log_all_errors: true
  graceful_degradation: true
  max_retry_attempts: 3
  
# Output and Reporting
reporting:
  default_format: "text"
  include_recommendations: true
  include_context: true
  max_code_snippet_lines: 5
  
  formats:
    json:
      pretty_print: true
      include_metadata: true
    sarif:
      schema_version: "2.1.0"
      include_fixes: false
    markdown:
      include_toc: true
      include_summary: true

# Integration Settings
integrations:
  mcp:
    timeout_seconds: 30
    max_request_size_mb: 10
    rate_limit_requests_per_minute: 100
  
  vscode:
    live_analysis: true
    max_diagnostics: 100
    debounce_ms: 500
  
  cli:
    colored_output: true
    progress_bar: true
    verbose_default: false