# Enterprise Configuration for SPEK Enhanced Development Platform
# Provides Six Sigma telemetry, supply chain security, and compliance matrix generation

enterprise:
  enabled: false  # Master switch - default OFF for backward compatibility
  
  # Six Sigma Quality Management
  sixsigma:
    enabled: true
    unit: "PR"  # Unit of measurement: PR (Pull Request) or Deploy
    sigma_shift: 1.5  # Industry standard 1.5 sigma shift
    target_sigma: 4.0  # Target sigma level (6210 DPMO)
    
    # Critical To Quality (CTQ) specifications
    ctqs:
      security:
        critical_max: 0
        high_max: 5
        opportunities_per_file: 3  # injection, authorization, crypto
      
      nasa_pot10:
        min_score: 0.90  # 90% compliance minimum
        opportunities_per_line: 1
      
      connascence:
        allow_positive_delta: false  # No increases allowed
        track_module_changes: true
      
      god_objects:
        max_delta: 0  # No new god objects
        size_threshold: 1000  # Lines of code threshold
      
      mece_dup:
        mece_min: 0.75  # Minimum MECE score
        dup_delta_max: 0  # No duplication increases
      
      tests_mutation:
        require_pass: true
        min_mutation_changed: 0.60  # 60% mutation score on changed lines
        allow_uncovered_changed: 0  # No uncovered new lines
      
      performance:
        max_regression_pct: 5  # 5% performance regression tolerance
        track_golden_workflows: true
    
    # Statistical Process Control
    spc:
      control_limits: "3_sigma"  # 3-sigma control limits
      detection_rules: ["nelson_rules", "western_electric"]
      chart_types: ["p_chart", "u_chart", "ewma"]
    
    # Theater Detection
    theater_detection:
      enabled: true
      cosmetic_critical_ratio_threshold: 10  # Alert if >10:1 cosmetic/critical
      reality_correlation_threshold: 0.7
      vanity_metric_detection: true

  # Supply Chain Security  
  supply_chain:
    enabled: true
    
    # Software Bill of Materials (SBOM)
    sbom:
      format: "CycloneDX"  # CycloneDX or SPDX
      version: "1.4"
      include_dev_dependencies: false
      license_detection: true
      vulnerability_scanning: true
    
    # Supply-chain Levels for Software Artifacts (SLSA)
    slsa:
      level: 3  # Target SLSA level (1-4)
      provenance_generation: true
      hermetic_builds: true
      reproducible_builds: true
      
    # Artifact Signing
    signing:
      enabled: true
      key_provider: "cosign"  # cosign, gpg, or custom
      sign_artifacts: true
      verify_signatures: true

  # Compliance Matrix
  compliance:
    enabled: true
    
    # Supported frameworks
    frameworks:
      - "SOC2"
      - "ISO27001" 
      - "NIST-SSDF"
      - "GDPR"
      - "HIPAA"  # Optional
    
    # SOC2 Trust Services Criteria
    soc2:
      security: true
      availability: true
      processing_integrity: true
      confidentiality: true
      privacy: true
      
    # ISO27001 Controls
    iso27001:
      version: "2022"
      annex_a_controls: true
      risk_assessment: true
      business_continuity: true
      
    # NIST Secure Software Development Framework
    nist_ssdf:
      version: "1.1"
      practices: ["PO", "PS", "PW", "RV"]  # All practice groups
      implementation_tiers: [1, 2, 3]  # Target all tiers
    
    # Evidence Collection
    evidence:
      retention_days: 90
      audit_trail: true
      automated_collection: true
      compliance_reporting: true

  # Performance and Monitoring
  performance:
    monitoring:
      enabled: true
      metrics_collection_interval: 60  # seconds
      performance_baseline: true
      regression_detection: true
      
    optimization:
      cache_enabled: true
      parallel_processing: true
      memory_optimization: true
      disk_optimization: true

  # Security Settings
  security:
    encryption:
      at_rest: true
      in_transit: true
      key_rotation: true
      
    access_control:
      rbac_enabled: true
      audit_logging: true
      session_management: true
      
    vulnerability_management:
      scanning_enabled: true
      auto_remediation: false
      risk_scoring: true

  # Integration Settings
  integration:
    analyzer_compatibility: true
    backward_compatible: true
    feature_flags: true
    hot_reload: true
    
    # Existing analyzer integration
    preserve_existing_config: true
    merge_conflicts_resolution: "enterprise_extends_existing"
    nasa_compliance_preservation: true

  # Artifact Management
  artifacts:
    base_path: ".claude/.artifacts/"
    retention_policy: "30_days"
    compression: true
    encryption: false  # Enable for sensitive data
    
    # Directory structure
    directories:
      sixsigma: "sixsigma/"
      compliance: "compliance/" 
      supply_chain: "supply_chain/"
      performance: "performance/"
      security: "security/"

  # Reporting and Dashboards
  reporting:
    formats: ["json", "yaml", "html", "csv"]
    dashboard_enabled: true
    real_time_updates: true
    email_notifications: false
    
    # Report scheduling
    schedules:
      daily: ["performance", "security"]
      weekly: ["compliance", "sixsigma"] 
      monthly: ["supply_chain", "audit"]

# Environment-specific overrides
environments:
  development:
    enterprise:
      compliance:
        evidence:
          retention_days: 7
      artifacts:
        retention_policy: "7_days"
        
  staging:
    enterprise:
      compliance:
        evidence:
          retention_days: 30
      performance:
        optimization:
          parallel_processing: false
          
  production:
    enterprise:
      security:
        encryption:
          at_rest: true
          in_transit: true
        access_control:
          audit_logging: true
      artifacts:
        encryption: true
        retention_policy: "90_days"

# Feature flags for gradual rollout
feature_flags:
  enterprise_sixsigma_rollout: 0  # 0-100% rollout percentage
  enterprise_compliance_rollout: 0
  enterprise_supply_chain_rollout: 0
  enterprise_full_feature_rollout: 0